apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-depl
  labels:
    app: statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      labels:
        app: statistics
    spec:
      containers:
        - name: statistics
          image: 666555811597.dkr.ecr.us-east-1.amazonaws.com/kuikpay-statistics-service:dev-a3f7855-1652460145554 # {"$imagepolicy": "flux-system:statistics"}
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: statistics
                  key: node_env
            - name: CONTAINER
              value: docker
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: statistics
            # An array of keys from the ConfigMap to create as files
            items:
              - key: "statistics.properties"
                path: ".env"
---
apiVersion: v1
kind: Service
metadata:
  name: statistics-srv
spec:
  selector:
    app: statistics
  ports:
    - name: statistics
      protocol: TCP
      port: 8080
      targetPort: 8080
