---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k8s
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default

