---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: orion
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: orion
  filterTags:
    pattern: '^dev-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc

